### ISSUE TITLE
event for lazyload

### ISSUE THREAD

**Issue by mwordpress** [richhollis/vticker#14]
Is there a way to get work with lazyload 
http://www.appelsiini.net/projects/lazyload

i use event In this way
jQuery(document).ready(function () {
jQuery('#ticker-s4').vTicker({
	speed: 450,
	pause: 3000,
	animation: 'fade',
	mousePause: true,
	height: 340,
	showItems: 4
});
});
jQuery('#ticker-s4').on('vticker.afterTick', function() {
	jQuery("img.lazy").lazyload();
});

But nothing happened

**Comment by richhollis** [comment]
If this is still a problem, please re-open and provide a link to some sample code that I can run. Thanks.
