### ISSUE TITLE
Centering Content

### ISSUE THREAD

**Issue by scgrant327** [richhollis/vticker#15]
This does not center the ticker on the page...how can I do that? Is something happening inside vTicker that negates any content centering?

                   <center> <div style="width:100%">
                        <div id="ticker" style="font-size:32px;margin-top:24px;display:none;width:100%">
                          <ul>
                            <li id="wxWavg">...</li>
                            <li id="wxTemp">...</li>
                            <li id="wxBaro">...</li>
                            <li id="wxDrain">...</li>
                            <li id="wxMrain">...</li>
                          </ul>
                        </div>
                    </div></center>

**Comment by scgrant327** [comment]
Fixed by setting CSS on TICKER to:
#ticker > ul {
    height: 100px;
    width: 100%;
    display: table-cell;
    vertical-align: middle;
    text-align: center;
}

**Comment by richhollis** [comment]
Yep - glad you got it working.
