### ISSUE TITLE
Direction down not working in v1.15

### ISSUE THREAD

**Issue by amit-brainstormforce** [richhollis/vticker#16]
Unfortunately, vTicker for down direction is not working and keep sliding up.
Here is pen - http://codepen.io/anon/pen/grMeGG

**Comment by richhollis** [comment]
Hi there

Yep - this is not supported - see the README

"Compared to the original, it does not support fading and the direction option is removed as the animation direction is based on next or previous item: up for next; and down for previous."

Cheers
