### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by rshimshock** [richhollis/vticker#18]
Rich, thanks for taking the time to create a fork of the original vTicker. The older version is used as an option in Drupal's Views Ticker module, and I was looking to see if we might be able to update to this version. I've caught a couple of issues, and I'll post about each.

First, whenever trying to use the code in Drupal's interface, I get the following javascript error:

> Uncaught TypeError: Cannot read property 'options' of undefined
> jquery.vticker.js line 78

Looks like the jQuery is running into a conflict with the Ajax code in Drupal Views used to preview query results. 

Line 78 refers to `var options = state.options;` within `startInterval`. I noticed there is an `if(!state) return;` line in `stopInterval` right after the `state` variable is defined. I added that line to `startInterval` as follows, and seems to fix the Views problem and still works as expected:

```javascript
    startInterval: function() {
      var state = $(this).data('state');
      if(!state) return;  // added this line
      var options = state.options;
      var initThis = this;
      state.intervalId = setInterval(function(){
        internal.nextUsePause.call( initThis );
      }, options.pause);
    },
```

Would you support making this change, or might this cause an issue elsewhere? Thanks.

**Comment by richhollis** [comment]
Hi! Yes - I'm just in the middle of moving the core source JS to coffeescript, so it's a little easier to read and update (and to prepare for fixing open issue #17). Funnily enough, I spotted this one whilst working through the source! It's been fixed locally. I'm hoping to get this out next week and will let you know when it's done.

**Comment by richhollis** [comment]
Hi @rshimshock 

Having looked closer at your issues, I get the impression you might be directly trying to swap out the old vTicker with this one (like-for-like), which I overlooked when I replied originally to your issues. This might not work as expected - this version wasn't specifically designed to be swappable.

startInterval is an internal function which should always be able to get the state, so if it isn't able to read the state then something else (bad) is happening. It shouldn't get that far. The latest version in development (1.2) will actually raise an exception now if the state isn't available when it should be.

The goals of this project are slightly different to the original vTicker. For example, there is no directional support which you have mentioned in #19. I don't plan to support this. 

Maybe you can take another look at your issues, let me know your findings and re-open your issues if necessary. 

If you can use the latest master version against any testing you do then that would be helpful:

https://raw.githubusercontent.com/richhollis/vticker/master/js/jquery.vticker.js

If you are able to provide a test page which reproduces any problems then that would also be helpful too.

You might also find the docs site useful:
http://richhollis.github.io/vticker/

Thanks!
