### ISSUE TITLE
Random items

### ISSUE THREAD

**Issue by gNesh01** [richhollis/vticker#21]
Hi,

I've been using your vticker for rss widget but I would like to make items random. Do you have any idea how to make this happend?

tnx

**Comment by richhollis** [comment]
This is beyond the scope of vTicker itself.

I would imagine you are handling the RSS items in JS.

Have a look this SO post to find a shuffle method for your RSS item array:
http://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array

Then insert the shuffled items into your UL and run your ticker.

Good luck!
